# Generated by Django 2.0.13 on 2019-11-13 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numbertoworld', '0002_auto_20191113_0648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number',
            name='given_number',
            field=models.IntegerField(default=1),
        ),
    ]
